todoproject/todoapp/urls.py
from django.urls import path,include

import todoapp
from . import views
app_name='todoapp'

urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteview.as_view(), name='cbvdelete')
]

todoproject/todoproject/urls.py
from todoproject import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
def __str__(self):
    return self.name

todoproject/todoapp/forms.py
from django import forms
from . models import Task

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import TodoForm
from . models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views here.

class TaskListview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'
class TaskDetailview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'
class TaskUpdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})
class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')





def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        task=request.POST.get('task','')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task=Task(name=task,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})
def delete(request,id):
    if request.method=='POST':
        task2=Task.objects.get(id=id)
        task2.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    task3=Task.objects.get(id=id)
    f=TodoForm(request.POST or None, instance=task3)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task3})

todoproject/todoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/todoapp/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token%}
    <p><b>Are you sure want to delete?</b></p>
    <input type="submit">
</form>
{% endblock %}

todoproject/todoapp/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ task.name }}</h5>
                    <p><b>{{ task.priority }}</b></p>
                    <p><b>{{ task.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Delete</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>
                </div>
</div>
{% endblock %}

todoproject/todoapp/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <input type="submit">
</form>
{% endblock %}

todoproject/todoapp/templates/home.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
    {% csrf_token %}
    <input class="form-control" type="text" name="task" placeholder="Enter task name"><br>
    <input class="form-control" type="text" name="priority" placeholder="Enter priority"><br>
    <input class="form-control" type="date" name="date" placeholder="Enter your date"><br>
    <input class="btn btn-success" type="submit">
</form>
        </div>
        <div class="col-md-6">
            {% for i in task1 %}
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p><b>{{ i.priority }}</b></p>
                    <p><b>{{ i.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Delete</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/todoapp/templates/home2.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
    {% csrf_token %}
    <input class="form-control" type="text" name="task" placeholder="Enter task name"><br>
    <input class="form-control" type="text" name="priority" placeholder="Enter priority"><br>
    <input class="form-control" type="date" name="date" placeholder="Enter your date"><br>
    <input class="btn btn-success" type="submit">
</form>
        </div>
        <div class="col-md-6">
            {% for i in task %}
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p><b>{{ i.priority }}</b></p>
                    <p><b>{{ i.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Delete</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/todoapp/templates/update.html
{% extends 'base.html' %}
{% block body %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}

                <input type="submit">
            </form>
        </div>
    </div>
</div>

{% endblock %}